#include "TCanvas.h"
#include "TFile.h"
#include "TH1D.h"
#include "TStyle.h"
#include <iostream>

void plotLumi()
{
  gStyle->SetOptStat(0);

  // 1. Open the AnalysisResults.root generated by MyUPC_Luminosity.cxx
  TFile* f = TFile::Open("AnalysisResults.root", "READ");
  if (!f || f->IsZombie()) {
    std::cerr << "Cannot open AnalysisResults.root" << std::endl;
    return;
  }

  // 2. Get the Skimmed events histogram
  TH1D* hEvents = (TH1D*)f->Get("my-upc-luminosity/hEvents_All");
  if (!hEvents) {
    std::cerr << "Cannot find hEvents_All in AnalysisResults.root" << std::endl;
    return;
  }

  // 3. Define the visible cross-section for the trigger used to produce the Skimmed Data
  // !!! IMPORTANT !!!
  // This cross-section depends on the collision system (pp, PbPb), energy, and year.
  // We use 50.0 mb as a placeholder for pp. REPLACE THIS with official ALICE values.
  double sigma_visible_mb = 50.0; // mb
  double sigma_visible_inver_nb = sigma_visible_mb * 1e6; // mb to nb

  // 4. Create a new histogram for Luminosity
  TH1D* hLumi = (TH1D*)hEvents->Clone("hLumi");
  hLumi->SetTitle("Integrated Luminosity per Run (Skimmed Data); Run Number; #mathcal{L}_{int} [nb^{-1}]");
  hLumi->Reset();

  // 5. Calculate Luminosity per run bin
  for (int i = 1; i <= hEvents->GetNbinsX(); i++) {
    double nEvents = hEvents->GetBinContent(i);
    if (nEvents > 0) {
      double lumi = nEvents / sigma_visible_inver_nb;
      double lumiErr = TMath::Sqrt(nEvents) / sigma_visible_inver_nb; // Counting error
      hLumi->SetBinContent(i, lumi);
      hLumi->SetBinError(i, lumiErr);
    }
  }

  // 6. Draw the result
  TCanvas* c = new TCanvas("cLumi", "Luminosity per Run", 800, 600);
  c->SetGrid();
  c->SetBottomMargin(0.12);
  c->SetLeftMargin(0.12);
  
  // Set nice marker and line style
  hLumi->SetMarkerStyle(20);
  hLumi->SetMarkerColor(kBlue);
  hLumi->SetLineColor(kBlue);
  
  // Adjust X-axis range to only show runs with data
  int firstBin = hLumi->FindFirstBinAbove(0);
  int lastBin = hLumi->FindLastBinAbove(0);
  if (firstBin > 0 && lastBin >= firstBin) {
    // Add small buffer
    hLumi->GetXaxis()->SetRange(firstBin - 2, lastBin + 2);
  }

  hLumi->Draw("P E");

  c->SaveAs("LuminosityPerRun.png");
  
  std::cout << "Successfully plotted Luminosity to LuminosityPerRun.png" << std::endl;
}
